Fabmo log is sent to USB
FabMo/FabMo-Engine pull request #845
Opened 2022-03-29 18:08 UTC by kyle-kingsbury

Grabs most recent /opt/fabmo/log text file and exports it to USB.

2022-03-31 17:09 UTC, RobMackie requested changes

2022-03-31 17:09 UTC, RobMackie commented on bin/collect_and_export_data_to_usb_drive
> +	my $currentFabmoLogFileName = "`cd /opt/fabmo/log; ls -lt *.txt | head -1 | cut -c 44-`";
the paths to ls, head and cut should be explicit and complete here.

2022-04-05 15:42 UTC, kyle-kingsbury commented
Ready for review.

2022-04-06 18:23 UTC, RobMackie approved these changes
looks good

2022-04-06 19:27 UTC, merged