Commented out sendM30 if stat 3 is received
FabMo/FabMo-Engine pull request #846
Opened 2022-04-04 19:01 UTC by kyle-kingsbury

Commented out 1 line in gcode runtime. Whenever g2 reported a stat 3, the program would end early by sending an m30. I could not find a good way to replicate this. It seemed very random. Sometimes it would happen 3 times in a row, sometimes it would not happen for 10 consecutive runs. Either way, my understanding is that stat:3 means that the queue is out of gcode but can be fed more. Sending an m30 just because of a stat 3 does not make any sense. The major setback of this change is the operator must put an m30 at the end of their file. I am adding an issue requesting that we enhance this however we see fit.

2022-04-06 19:34 UTC, RobMackie requested changes
I believe this the only place that "sendM30()" is invoked. Let's clean up. How about removing t he line here rather than commenting it out, and then remove the whole "sendM30()" function from g2.js. Then we don't need all the commnentary here in the file, and we can leave the commentary about what "used to be a problem" in the issue and pr, and the code is simpler to understand. sendM30() was always a kludge which was there to work around a problem that has been fixed in g2core, so it's all water under the bridge.  If anyone wants to find the history they can use git blame, find the commit and then find the issue and pr. 

Is that an ok ask? I think we need to build those habits. (I'm as bad as anyone at leaving comments about what used to be - so i'm asking that we start doing what I'm saying rather than what I've been doing up until now. :-)

2022-04-13 19:26 UTC, RobMackie commented
Testing - did the normal devchecks, then ran gcode ending in "end" and an M30 and M2 and ending in a "g1 x0 F150", with spindle having been run and stopped before that final line. 

Everything worked if the gcode ended in M30 or M2 or m30 or m2 but did not work right with "end" nor wtih "g1 ..." In the latter two cases it was necessary to use the escape key to abort the job, or else the job finished so no new job could be run.

Just as expected.

2022-04-13 19:27 UTC, RobMackie commented
closed by wrong click re-opened

2022-04-13 19:27 UTC, merged

2022-04-13 19:29 UTC, RobMackie reviewed
no need to make requested changes. we'll do that as a new issue.

2022-05-20 14:29 UTC, kyle-kingsbury commented
Forgot to close branch after squash and merge.